### PR TITLE
feat: generate netlify redirects for alias

### LINKED ISSUE #177: Make Antora generates Netlify redirects files for aliases
By default, Antora generates an html page that redirect using an http 200: extra static refresh html pages https://docs.antora.org/antora/2.3/playbook/urls-redirect-facility/#generated-static-html-refresh-pages.
It is able to generate Netlify `_redirects` file that will better manage redirections with http 301: 
https://docs.antora.org/antora/2.3/playbook/urls-redirect-facility/#generated-redirect-configuration-for-netlify.
We already defined redirects in the `netlify.toml` file but Netlify is able to manage configuration from both files, first using the `_redirects` file: https://docs.netlify.com/routing/redirects/#rule-processing-order

Be careful to keep the redirects as they are for the preview.
Prior to do it, ensure we can test the redirects in a dedicated environment and not only on production (see #168)

### PR DESCRIPTION
**Pull request by tbouffard**
Aliases are now generating true http 301 instead of http 200 via http page; this
will be better for SEO.
Update the 'type' argument to enable it for preview.

closes #177 

### For testers

The `_redirects` file is created is the same folder as the site content and is created for the production build.
The preview defaults don't change: redirects are managed by dedicated html pages (for file browsing or http servers without redirect capacities).

Redirects generation for preview tested locally with 
- preview creation:  `./build-preview-dev.bash --component bonita --branch 2021.2 --local-sources true --type netlify`
- then run dev server: `npm run serve`

### Figures
**Note**: generated with `./build-preview-dev.bash --local-sources --force-production-navbar --use-all-repositories --type netlify` 

We currently have **606 redirects**: [_redirects.txt](https://github.com/bonitasoft/bonita-documentation-site/files/7504305/_redirects.txt)
- most are for Bonita 2021.2 and 2022.1 (mainly after the introduction of Antora modules)
- Bonita 7.9, 7.10, 7.11 have 4 each, 2021.1 has 6
- 6 are for labs (bici)

Files and size of the generated site
- static html page redirects: 5 600 elements, 642,0 MB
- netlify redirects: 4 995 elements, 641,7 MB (606 redirect html pages removed, _redirects file added)

### CODE REVIEW

**Comment by alachambre** [comment]
Looks good 👍 

Juste a question, when I use the script with the following command: 

```
./build-preview-dev.bash \
  --use-multi-repositories \
  --component-with-branches bonita:2021.1,2021.2 \
  --force-production-navbar true \
  --local-sources true \
  --type netlify
```

It says in the logs that the prevy type is 'local,netlify', but I think it should only be netlify no? 

```
Running 'build-preview' with dev arguments (--type local --ci false)
Script Options: --type local --ci false --use-multi-repositories --component-with-branches bonita:2021.1,2021.2 --force-production-navbar true --local-sources true --type netlify
Assume script is NOT running on CI environment
Extra Antora Options: 
Generating an Antora Playbook for documentation content preview
PR: undefined
Site Url: undefined
Site Title: undefined
Antora Playbook source file loaded
Documentation content: multi components and branches
Components with branches: [ 'bonita:2021.1,2021.2' ]
Use Local Sources: true
Use Local UI Bundle: undefined
Preview Type: local,netlify
Fetch Sources: undefined
Force Production Navbar: true
--> Force usage of production navbar
Hide Edit Page Links: undefined
Hide Navbar Components List: undefined
Dumping yaml....
Antora Playbook generated in ./antora-playbook-content-for-preview.yml
Building preview...
asciidoctor: WARNING: skipping reference to missing attribute: varversion
asciidoctor: WARNING: skipping reference to missing attribute: varversion
asciidoctor: WARNING: skipping reference to missing attribute: varversion
asciidoctor: WARNING: skipping reference to missing attribute: varversion
asciidoctor: WARNING: release-notes.adoc: line 166: id assigned to section already in use: maintenance-compatibility
asciidoctor: WARNING: skipping reference to missing attribute: varversion
asciidoctor: WARNING: skipping reference to missing attribute: varversion
asciidoctor: WARNING: skipping reference to missing attribute: varversion
asciidoctor: WARNING: skipping reference to missing attribute: varversion
asciidoctor: WARNING: migrate-from-an-earlier-version-of-bonita.adoc: line 621: list item index: expected 1, got 3
asciidoctor: WARNING: migrate-from-an-earlier-version-of-bonita.adoc: line 625: list item index: expected 2, got 4
asciidoctor: WARNING: migrate-from-an-earlier-version-of-bonita.adoc: line 627: list item index: expected 3, got 5
```

**Comment by tbouffard** [comment]
About the preview type, I run your command on Ubuntu with commit 535fd0f and logs show `Preview Type: netlify` (the preview Antora playbook is correctly configured for netlify redirects generation)
`build-preview-dev.bash` already set the `type` argument to `local` so it is equivalent to `./build-preview.bash --type local --type netlify`. But I have managed this in the node script to only keep the latest passed value. 
So you shouldn't have `Preview Type: local,netlify` in the logs. In this case, the preview Antora playbook is not configured correctly at all.
I guess you are running the command on macOS. Does that mean we have a different behaviour on this OS?

Ubuntu 20.04.3 LTS
Node v14.17.3

**Comment by alachambre** [comment]
In the generated playbook, I have redirect_facility equals to static, I believe should be netlify no?

```
./build-preview-dev.bash \
  --use-multi-repositories \
  --component-with-branches bonita:2021.1,2021.2 \
  --force-production-navbar true \
  --local-sources true \
  --type netlify \
  --only-generate-playbook
```
-> 

```
Running 'build-preview' with dev arguments (--type local --ci false)
Script Options: --type local --ci false --use-multi-repositories --component-with-branches bonita:2021.1,2021.2 --force-production-navbar true --local-sources true --type netlify --only-generate-playbook
Assume script is NOT running on CI environment
Extra Antora Options: 
Generating an Antora Playbook for documentation content preview
PR: undefined
Site Url: undefined
Site Title: undefined
Antora Playbook source file loaded
Documentation content: multi components and branches
Components with branches: [ 'bonita:2021.1,2021.2' ]
Use Local Sources: true
Use Local UI Bundle: undefined
Preview Type: local,netlify
Fetch Sources: undefined
Force Production Navbar: true
--> Force usage of production navbar
Hide Edit Page Links: undefined
Hide Navbar Components List: undefined
Dumping yaml....
Antora Playbook generated in ./antora-playbook-content-for-preview.yml
Skip documentation generation
```

-> 

```
➜  bonita-documentation-site git:(feat/enable_netlify_redirect) cat ./antora-playbook-content-for-preview.yml 
# Generated from 'antora-playbook.yml'
site:
  title: Bonita Documentation
  url: https://documentation.bonitasoft.com/
  start_page: bonita::index.adoc
  robots: disallow
runtime:
  cache_dir: ./.cache/antora
  fetch: false
content:
  sources:
    - url: ../bonita-doc
      branches:
        - '2021.1'
        - '2021.2'
ui:
  bundle:
    url: ./resources/antora-ui-bundle.zip
asciidoc:
  extensions:
    - ./lib/source-url-include-processor.js
    - ./lib/json-config-ui-block-macro.js
    - ./lib/inline-man-macro.js
    - ./lib/multirow-table-head-tree-processor.js
    - ./lib/swagger-ui-block-macro.js
    - ./lib/tabs-block.js
urls:
  html_extension_style: drop
  redirect_facility: static
```

**Comment by alachambre** [comment]
Forget it, I wasn't up to date with the remote ^^'

**Review by alachambre — APPROVED** [review]

**Pull request merged**
