### PR TITLE
test: update title for bonita central on tests

### PR DESCRIPTION
**Pull request by benjaminParisel**

### CODE REVIEW

**Comment by benjaminParisel** [comment]
As you suggest @jeromecambon we keep Bonita Central as title for this component. So we re-adapt the test.

**Comment by tbouffard** [comment]
😸 All right, if everyone prefers "Bonita Central" to "Central", let's go!

**Review by jeromecambon — APPROVED** [review]
LGTM

**Review by tbouffard — CHANGES_REQUESTED** [review]
❌ Command fails locally

```
$ ./build-preview-dev.bash --use-test-sources
Running 'build-preview' with dev arguments (--type local)
Preparing the preview build
Script Options: --type local --use-test-sources
Generating an Antora Playbook for documentation content preview
PR: undefined
Site Url: undefined
Site Title: undefined
Start Page: undefined
Antora Playbook source file loaded
Documentation content: use test sources
Use Local Sources: undefined
Use Local UI Bundle: undefined
Use Default Antora UI Bundle: undefined
Preview Type: local
Fetch Sources: undefined
Force Production Navbar: undefined
Hide Edit Page Links: undefined
Hide Navbar Components List: undefined
Dumping yaml....
Antora Playbook generated in ./antora-playbook-content-for-preview.yml
Building the preview using Node v16.18.0...
[11:28:22.491] FATAL (antora): the start path 'test/documentation-content/central/1.0' does not exist in /mnt/toma/SharedData/development/bonita/docs/bonita-documentation-site (branch: tests/adapt_test_from_real_title_for_bonita_central <worktree>)
    Cause: Error
        at /development/bonita/docs/bonita-documentation-site/node_modules/@antora/content-aggregator/lib/aggregate-content.js:458:13
```

**Review by tbouffard — APPROVED** [review]
Building the site with test resources now works with commit 5859d5aa74e9a83e66e1f0bccf6d57d15f439030

image

**Pull request merged**
