### PR TITLE
doc: enhance the "troubleshooting" section

### PR DESCRIPTION
**Pull request by NathalieC**
* reword the existing sections
* add 2 additional information: subsections and grey areas

### CODE REVIEW

**Comment by NathalieC** [comment]
I cannot preview my formatting attempt. Hoping it will be fine.

**Comment by tbouffard** [comment]
> I cannot preview my formatting attempt. Hoping it will be fine.

@NathalieC you can display a preview by going to the `Files changed` tab of the Pull Request and then use the rich diff or view the full file.

preview_file

It seems that the block are not displayed as you mean it.

**Comment by NathalieC** [comment]
Indeed, this is not the way I'd like it to look like. 
I actually want no formatting: I just want to indicate **how to** create the grey area that you can see [here](https://documentation.bonitasoft.com/bonita/2021.2/identity/active-directory-or-ldap-authentication#_troubleshooting).
It looks like:
image
But again, I do not want that result in the contributing guide, I just want to pass on how to create it:

****
*Symptom*
*Cause*
*Possible Solutions*
****
I used [quote]. So, this is note "quote". What is it?
Can you help me?

**Comment by tbouffard** [comment]
Change with 8ce3eec
image

**Comment by NathalieC** [comment]
LGTM.

**Review by tbouffard — APPROVED** [review]

**Pull request merged**
